# Generated by Django 2.1.7 on 2019-03-18 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190315_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=50)),
                ('event_descr', models.CharField(default='', max_length=100)),
                ('event_name', models.CharField(default='', max_length=50)),
                ('event_type', models.CharField(default='', max_length=50)),
                ('number_going', models.IntegerField(default=-1)),
                ('location', models.CharField(default='', max_length=50)),
                ('lng', models.FloatField(default=-1)),
                ('lat', models.FloatField(default=-1)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='icon',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_descr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_going',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
