# Generated by Django 2.1.7 on 2019-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190318_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='event',
            name='lng',
            field=models.FloatField(default=-1),
        ),
    ]
