# Generated by Django 2.1.7 on 2019-03-31 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0008_auto_20190331_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users_going',
            field=models.ManyToManyField(related_name='upcoming_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
