# Generated by Django 2.1.7 on 2019-03-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_event_users_going'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(1, 'Not relevant'), (2, 'Review'), (3, 'Maybe relevant'), (4, 'Relevant'), (5, 'Leading candidate')], max_length=50),
        ),
    ]
