# Generated by Django 2.1.7 on 2019-03-15 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_descr',
            field=models.CharField(default='descr', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_going',
            field=models.IntegerField(default=0),
        ),
    ]
